<?php

use function Livewire\Volt\{title};

title('Bewerbungen - Übersicht');

?>

<x-intranet-app-bewerbungen::bewerbungen-layout heading="Bewerbungen App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-bewerbungen::bewerbungen-layout>